"""Expanded slang / profanity / WSB jargon symbols for the stoplist bucket."""

from __future__ import annotations

# Tokens that are overwhelmingly non-equity when they appear as $TICKER / ALLCAPS
# in Reddit finance threads. Keep real dual-use tickers (ON, ALL, IT, DD, AI, …)
# out of this set when they still trade — those are filtered by the live universe.
SLANG_STOPLIST: frozenset[str] = frozenset(
    {
        # function words / pronouns
        "A",
        "I",
        "AM",
        "AN",
        "AS",
        "AT",
        "BE",
        "BY",
        "DO",
        "GO",
        "HE",
        "IF",
        "IN",
        "IS",
        "ME",
        "MY",
        "NO",
        "OF",
        "OK",
        "OR",
        "SO",
        "TO",
        "UP",
        "US",
        "WE",
        "AND",
        "ARE",
        "FOR",
        "GET",
        "GOT",
        "HAS",
        "HER",
        "HEY",
        "HIS",
        "HOW",
        "ITS",
        "LET",
        "NOT",
        "NOW",
        "OFF",
        "OLD",
        "ONE",
        "OUR",
        "OUT",
        "OWN",
        "PER",
        "SAY",
        "SEE",
        "SET",
        "SHE",
        "THE",
        "TOO",
        "TOP",
        "TRY",
        "TWO",
        "USE",
        "VIA",
        "WAS",
        "WAY",
        "WHO",
        "WHY",
        "YES",
        "YOU",
        "THAT",
        "THEN",
        "THEY",
        "THIS",
        "THUS",
        "WHAT",
        "WHEN",
        "WILL",
        "WITH",
        "WERE",
        "HAVE",
        "FROM",
        "YOUR",
        "JUST",
        "LIKE",
        "SOME",
        "THEM",
        "THAN",
        "INTO",
        "OVER",
        "ALSO",
        "BACK",
        "ONLY",
        "COME",
        "MADE",
        "MOST",
        "MANY",
        "MUCH",
        "SUCH",
        "HERE",
        "EVEN",
        "VERY",
        "WELL",
        "BEEN",
        "MORE",
        # internet / WSB jargon
        "WSB",
        "YOLO",
        "FOMO",
        "HODL",
        "FUD",
        "LOL",
        "LMAO",
        "ROFL",
        "OMG",
        "WTF",
        "SMH",
        "TBH",
        "IDK",
        "IMO",
        "IMHO",
        "BRUH",
        "DUDE",
        "GUYS",
        "BRO",
        "SIR",
        "PLS",
        "PLZ",
        "PLEASE",
        "THANKS",
        "THX",
        "NP",
        "EDIT",
        "OP",
        "TLDR",
        "ELI5",
        "PSA",
        "NFW",
        "BAN",
        "BOT",
        "MOD",
        "TENDIES",
        "APES",
        "APE",
        "JPOW",
        "REEE",
        "GUH",
        "BAG",
        "BAGS",
        "BAGHOLDER",
        "DIAMOND",
        "HANDS",
        "PAPER",
        "ROCKET",
        "MOON",
        "MOONING",
        "LAMBO",
        "WAGMI",
        "NGMI",
        "HF",
        "CITADE",
        # trading chatter (not tickers we want in equity universe)
        "CEO",
        "CFO",
        "CTO",
        "IPO",
        "ETF",
        "ATH",
        "ATL",
        "AVG",
        "EOD",
        "EOW",
        "EPS",
        "FDA",
        "GDP",
        "IV",
        "OTM",
        "ITM",
        "AH",
        "PM",
        "PRE",
        "RSI",
        "MACD",
        "PT",
        "TA",
        "FA",
        "DD",
        "PR",
        "IR",
        "SEC",
        "FED",
        "FOMC",
        "CPI",
        "PCE",
        "OTC",
        "NYSE",
        "BUY",
        "SELL",
        "HOLD",
        "LONG",
        "SHORT",
        "PUT",
        "CALL",
        "CALLS",
        "PUTS",
        "BULL",
        "BEAR",
        "PUMP",
        "DUMP",
        "DIP",
        "RIPS",
        "RIP",
        "GAIN",
        "LOSS",
        "RISK",
        "SAFE",
        "PLAY",
        "PLAYS",
        "THESIS",
        "CATALYST",
        # profanity / sexual slang (cashtag spam)
        "ASS",
        "CUM",
        "COCK",
        "DICK",
        "SEX",
        "SEXY",
        "PORN",
        "FUCK",
        "FUCKED",
        "SHIT",
        "DAMN",
        "HELL",
        "BITCH",
        "PUSSY",
        "PENIS",
        "VAGINA",
        "ANUS",
        "ANAL",
        "SUCK",
        "SUCKS",
        "WHORE",
        "SLUT",
        "FAG",
        "GAY",
        "RAPE",
        "KILL",
        "DIE",
        "DEAD",
        "WTF",
        "STFU",
        "GTFO",
        "LMFAO",
        "WTF",
        "HORNY",
        "BOOBS",
        "TITS",
        "NIPS",
        "BUTT",
        "FART",
        "POOP",
        "PEE",
        "PISS",
        "CRAP",
        "HELL",
        "TAG",
        "NICE",
        "GOOD",
        "BAD",
        "FREE",
        "HELP",
        "NEED",
        "WANT",
        "LOVE",
        "HATE",
        "HOPE",
        "WOW",
        "YES",
        "NOPE",
        "MAYBE",
        "SURE",
        "OKAY",
        "TRUE",
        "FALSE",
        "NEXT",
        "LAST",
        "BEST",
        "WORST",
        "HIGH",
        "LOW",
        "BIG",
        "TINY",
        "HUGE",
        "NEAR",
        "FAR",
        "SOON",
        "LATE",
        "EARLY",
        "TODAY",
        "TOMORROW",
        "YESTERDAY",
        "WEEK",
        "YEAR",
        "TIME",
        "MONEY",
        "CASH",
        "RICH",
        "POOR",
        "BROKE",
        "TRASH",
        "GARBAGE",
        "JUNK",
        "SCAM",
        "FRAUD",
        "FAKE",
        "REAL",
        "JOKE",
        "MEME",
        "HYPE",
        "NOISE",
        "COPE",
        "SEETHE",
        "MALD",
        "BASED",
        "CRINGE",
        "KEK",
        "POG",
        "POGGERS",
        # flagged review-bucket slang / misspellings
        "DEEZ",
        "RTRD",
        "CUCK",
        "JIZZ",
        "DIX",
        "PNIS",
        "CUNT",
        "DONG",
        "ROPED",
        "ROPES",
        "TONK",
        "CLIT",
        "BLOW",
        "FUK",
        "JELQ",
        "TIT",
        "FAP",
        "DICKS",
        "GAPE",
        "PNUS",
        "CKING",
        "HIHI",
        "NUTS",
        "BALLS",
        "BONER",
        "WEEN",
        "WANG",
        "SCHLONG",
        # foreign-suffix heuristic false positives (F/Y/Q)
        "BECKY",
        "BCKY",
        "BABY",
        "MILF",
        "GAYMF",
        "TSLAQ",  # anti-Tesla short community tag, not bankrupt TSLA
        "PSSY",
        "SENY",
    }
)


# English / slang bases that falsely trip the 5th-letter F/Y/Q ADR/bankruptcy rule.
# Matched against symbol with the trailing F/Y/Q stripped (e.g. BECKY → BECK).
FOREIGN_SUFFIX_FALSE_BASES: frozenset[str] = frozenset(
    {
        "BECK",
        "BCK",
        "BAB",
        "BABY",  # BABY itself; BABYF kept via ratio exception when symbol not in stoplist
        "MIL",
        "MILF",
        "GAY",
        "GAYM",
        "PSS",
        "SEN",
    }
)


def foreign_suffix_base(symbol: str) -> str:
    """Strip a trailing F/Y/Q used by the NASDAQ 5th-letter foreign heuristic."""
    symbol = symbol.upper()
    if len(symbol) >= 2 and symbol[-1] in "FYQ":
        return symbol[:-1]
    return symbol


def should_drop_foreign_suffix(
    symbol: str,
    *,
    cashtag_count: int,
    allcaps_count: int,
) -> tuple[bool, str]:
    """Return (drop?, reason) for review_foreign false positives.

    Drop when:
    - full symbol is on the slang stoplist, or
    - base (strip F/Y/Q) is slang/common-word — except real OTC ``*F`` rows whose
      all-caps/cashtag ratio looks ticker-like (keeps BABYF while dropping BABY), or
    - all-caps > 10× cashtag and symbol/base hits slang/common words.
    """
    symbol = symbol.upper()
    base = foreign_suffix_base(symbol)
    ratio_ok = cashtag_count > 0 and allcaps_count <= 10 * cashtag_count

    if symbol in SLANG_STOPLIST:
        return True, "symbol_in_stoplist"

    base_hit = base in SLANG_STOPLIST or base in FOREIGN_SUFFIX_FALSE_BASES
    if base_hit:
        # Keep plausible foreign OTC (…F) when the *symbol* itself is not slang
        # and cashtag density is not word-like (e.g. BABYF).
        if symbol.endswith("F") and symbol not in SLANG_STOPLIST and ratio_ok:
            pass
        else:
            return True, f"base_in_slang_or_common:{base}"

    if cashtag_count > 0 and allcaps_count > 10 * cashtag_count:
        if (
            symbol in SLANG_STOPLIST
            or base in SLANG_STOPLIST
            or base in FOREIGN_SUFFIX_FALSE_BASES
            or symbol in FOREIGN_SUFFIX_FALSE_BASES
        ):
            return True, "high_allcaps_and_slang"

    return False, ""
